publish_to: none
version: 0.0.0

name: xpa
description: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - dummy/

  fonts:
  - family: NanumSquareNeo
    fonts:
      - asset: fonts/NanumSquareNeoOTF-aLt.otf
        weight: 300
      - asset: fonts/NanumSquareNeoOTF-bRg.otf
        weight: 400
      - asset: fonts/NanumSquareNeoOTF-cBd.otf
        weight: 500
      - asset: fonts/NanumSquareNeoOTF-dEb.otf
        weight: 600
      - asset: fonts/NanumSquareNeoOTF-eHv.otf
        weight: 700
  - family: JetBrainsMono
    fonts:
      - asset: fonts/JetBrainsMono-Thin.ttf
        weight: 100
      - asset: fonts/JetBrainsMono-ThinItalic.ttf
        style: italic
        weight: 100
      - asset: fonts/JetBrainsMono-ExtraLight.ttf
        weight: 200
      - asset: fonts/JetBrainsMono-ExtraLightItalic.ttf
        style: italic
        weight: 200
      - asset: fonts/JetBrainsMono-Light.ttf
        weight: 300
      - asset: fonts/JetBrainsMono-LightItalic.ttf
        style: italic
        weight: 300
      - asset: fonts/JetBrainsMono-Regular.ttf
        weight: 400
      - asset: fonts/JetBrainsMono-Italic.ttf
        style: italic
        weight: 400
      - asset: fonts/JetBrainsMono-Medium.ttf
        weight: 500
      - asset: fonts/JetBrainsMono-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: fonts/JetBrainsMono-SemiBold.ttf
        weight: 600
      - asset: fonts/JetBrainsMono-SemiBoldItalic.ttf
        style: italic
        weight: 600
      - asset: fonts/JetBrainsMono-Bold.ttf
        weight: 700
      - asset: fonts/JetBrainsMono-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: fonts/JetBrainsMono-ExtraBold.ttf
        weight: 800
      - asset: fonts/JetBrainsMono-ExtraBoldItalic.ttf
        style: italic
        weight: 800