publish_to: none
version: 0.0.0

name: xpa
description: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: NanumSquareNeo
    fonts:
      - asset: assets/fonts/NanumSquareNeoOTF-aLt.otf
        weight: 300
      - asset: assets/fonts/NanumSquareNeoOTF-bRg.otf
        weight: 400
      - asset: assets/fonts/NanumSquareNeoOTF-cBd.otf
        weight: 500
      - asset: assets/fonts/NanumSquareNeoOTF-dEb.otf
        weight: 600
      - asset: assets/fonts/NanumSquareNeoOTF-eHv.otf
        weight: 700